### ISSUE TITLE
ModbusTcpServer constructor error (ArgumentOutOfRangeException for listen port)

### ISSUE THREAD

**Issue by vadmyst** [AM-WD/AMWD.Protocols.Modbus#2]
ModbusTcpServer constructor fails when validating listenPort.

The error:

Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'listenPort')
   at AMWD.Protocols.Modbus.Tcp.ModbusTcpServer..ctor(IPAddress listenAddress, Int32 listenPort)

**Comment by AndreasAmMueller** [comment]
Should be fixed with [v0.3.1](https://github.com/AM-WD/AMWD.Protocols.Modbus/compare/v0.3.0...v0.3.1).

**Comment by AndreasAmMueller** [comment]
I have really no idea what was wrong in my head when implementing the range validation - sry^^
