### ISSUE TITLE
Modbus RTU over TCP don't reply Data

### ISSUE THREAD

**Issue by truongsontech** [AM-WD/AMWD.Protocols.Modbus#3]
- With v0.3.1 or v0.3.1-2, I test with **Modbus Slave**, mode Modbus TCP is OK, but add:
 using var client = new ModbusTcpClient(host, port)
{
    Protocol = new RtuOverTcpProtocol(),
}; 
to use RtuOverTcp Protocol (and use this mode in **Modbus Slave**) then has no data reply, Admin please check for me!

**Comment by AndreasAmMueller** [comment]
Hi,
can you give me more information on RTU over TCP implemented on your slave device, you try to reach?

I searched a lot and came up with this documentation, I used to implement that kind of protocol:
https://www.fernhillsoftware.com/help/drivers/modbus/modbus-protocol.html

Maybe you can use the plain RTU protocol with a TCP client?
```cs
using var client = new ModbusTcpClient("hostname")
{
    Protocol = new RtuProtocol()
};
// [...] do other stuff
```

Thank you!

Andy

**Comment by truongsontech** [comment]
Tôi chỉ là đang test thử chế độ RTU over Modbus TCP. Tuy nhiên theo link của bạn cung cấp thì có vẻ như message của nó khác so với phần mềm test: Modbus Poll + Modbus Slave 
![image](https://github.com/user-attachments/assets/939bdc46-f097-4ea2-a5c1-fa115915c320)
![image](https://github.com/user-attachments/assets/acd44b53-4e6d-4bdb-b78f-02a97bb6b025)
and your protocol: 
![image](https://github.com/user-attachments/assets/33535c6f-c937-4208-b06e-0cd00cbf23a5)

**Comment by AndreasAmMueller** [comment]
Ok, thanks for the information.
I'll check that soon.

**Comment by AndreasAmMueller** [comment]
I checked your information with the result, that you should use the `RtuProtocol` only.

I tried to clarify the protocols in the docs, see this commit: https://github.com/AM-WD/AMWD.Protocols.Modbus/commit/e830e43c363323a009836e52ff1230a8405f2845

No bug, feature :wink:
