### ISSUE TITLE
strong named nuget packages

### ISSUE THREAD

**Issue by gnampf89** [AM-WD/AMWD.Protocols.Modbus#4]
Hi Andreas,

is it possible to provide strongly named assemblies in the nuget packages? This is required when included in an strongly named project.

Best regards
Michael

**Comment by AndreasAmMueller** [comment]
Hi Michael,

A quick look into strong naming seems only to work on Windows machines.

As my build pipeline is using a Docker .NET 8.0 container, I doubt, it'll work.    
But I'll check, whether it could be done somehow.

**Comment by AndreasAmMueller** [comment]
Hi Michael,

after a little research, I tried something out.

Can you verify, that the packages are now strong-named?

https://nuget.am-wd.de/packages/amwd.protocols.modbus.common/0.3.2-strong-named-assembly.2

**Comment by AndreasAmMueller** [comment]
Hi Michael,

done in commit https://github.com/AM-WD/AMWD.Protocols.Modbus/commit/3e8f2cd73b7b61759de56cb1e72111d4c8e5fa2e (v0.3.2) 😉

Andy

**Comment by gnampf89** [comment]
thank you, it works
