### ISSUE TITLE
does not work properly when proxy serial throw tcp

### ISSUE THREAD

**Issue by shamork** [AM-WD/AMWD.Protocols.Modbus#5]
I use Proxy to share ModBusRtu throw tcp Server(ModBusTcp). Then I can use one device by two different processes.
When client A is connected, everything is fine.
When client B is connected, only B can receive response bytes, A receive nothing after cmd sent.

**Comment by AndreasAmMueller** [comment]
Just for me to understand your setup:

```
Client A ==>  |    Proxy    |
              | TCP --> RTU | ==> RTU Modbus device
Client B ==>  |             |
```

and after connecting Client B, Client A does not work properly anymore, correct?

**Comment by shamork** [comment]
correct!

- SlaveId/UnitId: 11
- Type of request: WriteSingleRegister//00 01 00 00 00 06 0B 06 00 01 00 01 
- Interval of requests: send by hand, not stable

```csharp
var mc = new ModbusSerialConnection()
        {
            BaudRate = ((BaudRate)options.BaudRate),//38400
            DataBits = options.DataBits,//8
            StopBits = options.StopBits,//1
            Parity = options.Parity,//None
            PortName = options.ComName,//COM61
            Handshake = Handshake.None,
            ReadTimeout = TimeSpan.FromSeconds(5),
            WriteTimeout = TimeSpan.FromSeconds(5),
            ConnectTimeout = TimeSpan.FromSeconds(5),
            IdleTimeout = TimeSpan.FromSeconds(5),
            RtsEnable = false,
            DriverEnabledRS485 = false,
        };
        var cts = new CancellationTokenSource();
        using var rtu = new ModbusSerialClient(mc, true);
        //ListenIp: 0.0.0.0  ListenPort:7039
        using var proxy=new ModbusTcpProxy(rtu, IPAddress.Parse(options.ListenIp), options.ListenPort)
        {
            ReadWriteTimeout = TimeSpan.FromSeconds(5),//default is 0
        };
        await proxy.StartAsync(cts.Token);
        Console.WriteLine("Running...");
        Console.CancelKeyPress += (s,e) => { cts.Cancel(); };
        while (proxy.IsRunning)
        {
            cts.Token.WaitHandle.WaitOne();
        }

        await proxy.StopAsync(cts.Token);
        return 0;
```

**Comment by shamork** [comment]
It turns out to be my fault! Sorry for wasting your time!

When i change `ReadWriteTimeout = TimeSpan.FromSeconds(5),` to `ReadWriteTimeout = Timeout.InfiniteTimeSpan,`, everything works fine!

**Comment by shamork** [comment]
I'm closing this issue. You can reopen it if necessary.

**Comment by AndreasAmMueller** [comment]
Hi,
thank you for your feedback and I'm glad you could solve the problem for yourself.

I'll keep it in my personal backlog and try to verify some options when I get access to a physical device again.

Maybe there is something to enhance ;-)
